name: Run test

on:
  pull_request:
    branches: [master]

jobs:
  test_unit:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug


  test_instrumented:
    name: Instrumented Tests
    needs: test_unit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Android SDK components
        run: |
          sdkmanager --install "platform-tools" "emulator" "system-images;android-34;google_apis;x86"
          yes | sdkmanager --licenses

      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86
          profile: Nexus 6
          emulator-options: '-no-snapshot-load -no-window -noaudio'
          script: ./gradlew connectedCheck --stacktrace