name: Run test

on:
  pull_request:
    branches: [master]

env:
  JAVA_DISTRIBUTION: 'adopt'
  JAVA_VERSION: 21
  API_LEVEL: 29
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: |
          SKIP_ERRORPRONE=true SKIP_JAVADOC=true \
          ./gradlew assemble

  checks:
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Check Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Check lint
        run: ./gradlew lint

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [checks, build]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug --stacktrace

      - name: Upload unit Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test_results_${{ matrix.api-versions }}
          path: '**/build/test-results/**/TEST-*.xml'

  instrumentation-tests:
    name: Instrumentation Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: [checks, build]

    steps:
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls /dev/kvm

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.API_LEVEL }}
          script: ./gradlew connectedCheck --stacktrace
        env:
          API_LEVEL: ${{ env.API_LEVEL }}

      - name: Upload instrumentation test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ env.API_LEVEL }}
          path: |
            **/build/reports/*
            **/build/outputs/*/connected/*

  generate-jacoco-report:
    name: Generate JaCoCo Report
    runs-on: ubuntu-latest
    needs: [ unit-tests, instrumentation-tests ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate JaCoCo Report
        run: ./gradlew jacocoRootReport

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/jacocoRootReport/html/index.html

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coveralls-token: ${{ env.COVERALLS }}
        env:
          COVERALLS_REPO_TOKEN: ${{ env.COVERALLS }}